version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - app_network

  web:
    build: .
    container_name: django_app
    command: python main.py
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    networks:     
      - app_network



networks:
  app_network:
    driver: bridge
