version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - app_network

  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core worker -l info
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
