server:
  port: 8081
  address: 0.0.0.0

spring:
  application:
    name: product-pu
  data:
    redis:
      host: ${REDIS_HOST:192.168.137.70}
      port: 6379
logging:
  level:
    org.springframework.data.redis: DEBUG
    com.example.flashsale: DEBUG